### ISSUE TITLE
Improve Player States

### ISSUE THREAD

**Issue by avivajpeyi** [kickflip-games/github_game_off_2024#27]
Maybe: 
- 'Hooked' state (when the player reaches the end of the grappling hook)
- Death state
- Attack state
- Split Airborne --> jump + Falling states (maybe a subclass of the airborne state?)

https://www.gdquest.com/tutorial/godot/design-patterns/finite-state-machine/

**Comment by nsamelson** [comment]
So I created different substates and stuff. will need to look how to move code blocks into each particular state
